// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:rentease/features/customers/data/models/customer_hive_model.dart';
import 'package:rentease/features/inventory/data/models/inventory_item_hive_model.dart';
import 'package:rentease/features/rentals/data/models/rental_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerHiveModelAdapter());
    registerAdapter(InventoryItemHiveModelAdapter());
    registerAdapter(RentalHiveModelAdapter());
  }
}
